services:
  db:
    image: postgres:15-alpine
    container_name: puente-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tradingapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: puente-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tradingapp
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - JWT_SECRET=puente-trading-app-jwt-secret-key-must-be-at-least-256-bits-long
      - ALLOWED_ORIGINS=http://localhost
      - ALPHAVANTAGE_API_KEY=C6QI2GVRR5765JRQ
      - STOCK_SYMBOLS=AAPL,MSFT,GOOGL,AMZN,TSLA,META,NVDA,JPM,V,WMT
      - CRYPTO_SYMBOLS=BTC,ETH,BNB,XRP,ADA,SOL,DOGE,DOT,AVAX,MATIC
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: puente-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres-data:
